services:
  - type: web
    name: fanta-mondiali-2026
    runtime: python
    rootDir: .            # cambia se il branch ha una subdirectory
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: mondiali-2026
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fanta-mondiali-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FOOTBALL_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_URL
        value: https://fanta-mondiali-2026.onrender.com
      - key: EMAIL_FROM_ADDRESS
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"

databases:
  - name: fanta-mondiali-db
    databaseName: fantamondiali
    plan: free
