"""schema iniziale

Revision ID: 46f66cf35f6a
Revises: 
Create Date: 2026-07-08 14:45:15.206458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f66cf35f6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giocatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_giocatore', sa.Text(), nullable=False),
    sa.Column('squadra', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giocatori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giocatori_squadra'), ['squadra'], unique=False)

    op.create_table('partite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giornata', sa.Integer(), nullable=False),
    sa.Column('squadra_casa', sa.Text(), nullable=False),
    sa.Column('squadra_ospite', sa.Text(), nullable=False),
    sa.Column('risultato_casa_reale', sa.Integer(), nullable=True),
    sa.Column('risultato_ospite_reale', sa.Integer(), nullable=True),
    sa.Column('marcatore_reale', sa.Text(), nullable=True),
    sa.Column('pronosticabile', sa.Boolean(), nullable=False),
    sa.Column('data_ora_partita', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partite_giornata'), ['giornata'], unique=False)

    op.create_table('risultati_finali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squadra_1', sa.Text(), nullable=True),
    sa.Column('squadra_2', sa.Text(), nullable=True),
    sa.Column('squadra_3', sa.Text(), nullable=True),
    sa.Column('squadra_4', sa.Text(), nullable=True),
    sa.Column('capocannoniere', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stato_giornata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giornata', sa.Integer(), nullable=False),
    sa.Column('is_attiva', sa.Boolean(), nullable=False),
    sa.Column('is_in_archivio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giornata')
    )
    op.create_table('stato_pronostici_iniziali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_utente', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_temp_password', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_utente')
    )
    op.create_table('pronostici_giornata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('id_partita', sa.Integer(), nullable=False),
    sa.Column('esito_pronosticato', sa.Text(), nullable=True),
    sa.Column('risultato_casa_pronosticato', sa.Integer(), nullable=True),
    sa.Column('risultato_ospite_pronosticato', sa.Integer(), nullable=True),
    sa.Column('marcatore_pronosticato', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_partita'], ['partite.id'], ),
    sa.ForeignKeyConstraint(['id_utente'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronostici_giornata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronostici_giornata_id_partita'), ['id_partita'], unique=False)
        batch_op.create_index(batch_op.f('ix_pronostici_giornata_id_utente'), ['id_utente'], unique=False)

    op.create_table('pronostici_iniziali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('squadra_1', sa.Text(), nullable=True),
    sa.Column('squadra_2', sa.Text(), nullable=True),
    sa.Column('squadra_3', sa.Text(), nullable=True),
    sa.Column('squadra_4', sa.Text(), nullable=True),
    sa.Column('capocannoniere', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_utente'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronostici_iniziali', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronostici_iniziali_id_utente'), ['id_utente'], unique=False)

    op.create_table('punteggi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('punteggio_totale', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_utente'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_utente')
    )
    op.create_table('punteggi_giornata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('giornata', sa.Integer(), nullable=False),
    sa.Column('punti', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_utente'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_utente', 'giornata', name='uq_punteggio_giornata')
    )
    with op.batch_alter_table('punteggi_giornata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_punteggi_giornata_id_utente'), ['id_utente'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punteggi_giornata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_punteggi_giornata_id_utente'))

    op.drop_table('punteggi_giornata')
    op.drop_table('punteggi')
    with op.batch_alter_table('pronostici_iniziali', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronostici_iniziali_id_utente'))

    op.drop_table('pronostici_iniziali')
    with op.batch_alter_table('pronostici_giornata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronostici_giornata_id_utente'))
        batch_op.drop_index(batch_op.f('ix_pronostici_giornata_id_partita'))

    op.drop_table('pronostici_giornata')
    op.drop_table('utenti')
    op.drop_table('stato_pronostici_iniziali')
    op.drop_table('stato_giornata')
    op.drop_table('risultati_finali')
    with op.batch_alter_table('partite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partite_giornata'))

    op.drop_table('partite')
    with op.batch_alter_table('giocatori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giocatori_squadra'))

    op.drop_table('giocatori')
    # ### end Alembic commands ###
